### ISSUE TITLE
GUI broken (small things)

### ISSUE THREAD

**Issue by HyperRaccoon13** [The-Shortman/Planets-And-Portals-3#1]
after loading in the modpack the default ui scale over laps with the test build message and the modpack version:

![image](https://github.com/The-Shortman/Planets-And-Portals-3/assets/68512889/7206f513-a3ca-4e30-9672-f4cc0b2e6051)

**Comment by HyperRaccoon13** [comment]
ui texture mis match
on the settings screen, the credits and attributions button is a different texture
![image](https://github.com/The-Shortman/Planets-And-Portals-3/assets/68512889/95b5a1f7-0928-4258-9a84-e990ae1ce015)

**Comment by The-Shortman** [comment]
Fixed in Pre-release v002
