### ISSUE TITLE
UX notes for new installs.

### ISSUE THREAD

**Issue by Laskyyy** [The-Shortman/Planets-And-Portals-3#3]
**Describe the bug**
Default keybinds in the install did not have questbook bound to 'J' as the questbook implies (& I assume any other controls which you might want to have been customised).

The 'create questing' blueprint was also not given on world creation (only the Advanced Peripherals book, can be disabled in advancedperipherals/world.toml for clutter removal)

**To Reproduce (if applicable)**
- Present on a fresh prism install

**Version information:**
 - Windows 10
 - Pre-release v001
 - Installed through **Prism Launcher**

**Comment by The-Shortman** [comment]
Ah yes, I forgot to do that, I'll get around to it sometime this week

**Comment by The-Shortman** [comment]
Should be fixed in Pre-release v003

**Comment by The-Shortman** [comment]
Turns out absolutely none of this was fixed in pre-release v003, it's now fixed in v0.8
