### ISSUE TITLE
Links in quest book.

### ISSUE THREAD

**Issue by Laskyyy** [The-Shortman/Planets-And-Portals-3#4]
**Is your feature request related to a problem? Please describe.**
Noted about not having clickable links in QB

**Describe the solution you'd like**
Images in the book can be given 'onclick' events to URLs
Add a small 32x32 .png in the kubejs assets folder for a tiny github logo for people to click on perhaps? (or use a placeholder like I have here)
![image](https://github.com/The-Shortman/Planets-And-Portals-3/assets/73845178/5d413fac-1a91-4201-8943-a06202560128)
![image](https://github.com/The-Shortman/Planets-And-Portals-3/assets/73845178/385de514-5791-4df4-a616-747972d40b88)

**Comment by The-Shortman** [comment]
Added in Pre-release v002
