### ISSUE TITLE
Tetra compatibility

### ISSUE THREAD

**Issue by HyperRaccoon13** [The-Shortman/Planets-And-Portals-3#5]
**Describe the bug**
attempting to make a Tetra Hammer, with Maple Planks (Regions Unexplored) nothign happened

**To Reproduce (if applicable)**
Load into world, place down crafting table, then place in the recipe of:
P: plank of some form, from Regions Unexplored
S: stick
#: blank

#P#
#SP
S##

**Expected behavior**
Expected all wood types to be accepted

**Screenshots**
![image](https://github.com/The-Shortman/Planets-And-Portals-3/assets/68512889/7053ad85-db80-4ba5-ad64-12e9429250b0)

**Version information:**
 - OS: Windows 11
 - Modpack Version Pre-release v001

**Comment by HyperRaccoon13** [comment]
After playing more it seem none of the Regions Unexplored plansk can be used as planks

**Comment by The-Shortman** [comment]
Did a temporary fix to this by adding a quest that gives you an oak sapling so you can at least make the hammer.

I'll have to add the Regions Unexplored wood types to the tetra materials list at some point in the future

**Comment by HyperRaccoon13** [comment]
> Did a temporary fix to this by adding a quest that gives you an oak sapling so you can at least make the hammer.
> 
> I'll have to add the Regions Unexplored wood types to the tetra materials list at some point in the future

i could cook if need be

**Comment by The-Shortman** [comment]
Sure, make a PR to the dev branch if you want

**Comment by The-Shortman** [comment]
Tetra will be removed in Pre-release v004, so I'm marking this as

**Comment by The-Shortman** [comment]
Tetra will be removed in Pre-release v004, so I'm marking this as will not fix
